"""
Blog history model for MongoDB.
Handles storage and retrieval of generated blogs.
"""
from datetime import datetime
from bson import ObjectId
from utils.db import get_db
from utils.logger import setup_logger

logger = setup_logger(__name__)


class BlogHistory:
    """Blog history model for storing generated blogs."""
    
    collection_name = 'blog_history'
    
    @staticmethod
    def create_blog_entry(user_id, website_url, keywords, generated_blog, blog_config):
        """
        Create a new blog history entry.
        
        Args:
            user_id (str): User's ID
            website_url (str): Original website URL
            keywords (list): Extracted keywords
            generated_blog (str): Generated blog content
            blog_config (dict): Blog generation configuration (length, tone, etc.)
            
        Returns:
            dict: Created blog history document
        """
        db = get_db()
        
        blog_doc = {
            'user_id': ObjectId(user_id),
            'website_url': website_url,
            'keywords': keywords,
            'generated_blog': generated_blog,
            'blog_config': blog_config,
            'created_at': datetime.utcnow()
        }
        
        result = db[BlogHistory.collection_name].insert_one(blog_doc)
        blog_doc['_id'] = result.inserted_id
        
        logger.info(f"Blog history entry created for user: {user_id}")
        return blog_doc
    
    @staticmethod
    def get_user_history(user_id, limit=10, skip=0):
        """
        Get blog generation history for a user.
        
        Args:
            user_id (str): User's ID
            limit (int): Number of entries to return
            skip (int): Number of entries to skip (for pagination)
            
        Returns:
            list: List of blog history documents
        """
        db = get_db()
        
        cursor = db[BlogHistory.collection_name].find(
            {'user_id': ObjectId(user_id)}
        ).sort('created_at', -1).skip(skip).limit(limit)
        
        return list(cursor)
    
    @staticmethod
    def get_blog_by_id(blog_id, user_id):
        """
        Get a specific blog entry by ID (with user verification).
        
        Args:
            blog_id (str): Blog entry ID
            user_id (str): User's ID (for authorization)
            
        Returns:
            dict or None: Blog history document if found and authorized
        """
        db = get_db()
        
        try:
            return db[BlogHistory.collection_name].find_one({
                '_id': ObjectId(blog_id),
                'user_id': ObjectId(user_id)
            })
        except Exception:
            return None
    
    @staticmethod
    def count_user_blogs(user_id):
        """
        Count total blogs generated by a user.
        
        Args:
            user_id (str): User's ID
            
        Returns:
            int: Total number of blogs
        """
        db = get_db()
        return db[BlogHistory.collection_name].count_documents(
            {'user_id': ObjectId(user_id)}
        )
    
    @staticmethod
    def to_dict(blog_doc):
        """
        Convert blog document to dictionary (safe for API response).
        
        Args:
            blog_doc (dict): Blog document from database
            
        Returns:
            dict: Safe blog data for API response
        """
        if not blog_doc:
            return None
        
        return {
            'id': str(blog_doc['_id']),
            'user_id': str(blog_doc['user_id']),
            'website_url': blog_doc['website_url'],
            'keywords': blog_doc['keywords'],
            'generated_blog': blog_doc['generated_blog'],
            'blog_config': blog_doc.get('blog_config', {}),
            'created_at': blog_doc['created_at'].isoformat()
        }
